version: "3.9"

services:

  back-end:
    container_name: api
    build: ./back-end
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env
  
  front-end:
    container_name: spa
    build: ./front-end
    env_file:
      - ./front-end/.env.local
    volumes:
      - next-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443

    volumes:
      - next-volume:/var/www/html
    depends_on:
      - back-end
      - front-end

volumes:
  next-volume: 
