version: "3.9"

services:

  back-end:
    container_name: api
    build: ./back-end
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env
  
  front-end:
    container_name: spa
    build: ./front-end
    env_file:
      - ./front-end/.env.local
    volumes:
      - next-volume:/var/www/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ssl-certs:/etc/letsencrypt
      - next-volume:/var/www/html
    command: certonly --webroot --agree-tos --email marcelo.leda@icomp.ufam.edu.br -w /var/www/html -d rifasrioamazonas.com.br -d www.rifasrioamazonas.com.br

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 8080:80
      - 443:443

    volumes:
      - next-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - back-end
      - front-end
      - certbot

volumes:
  next-volume: 
  ssl-certs:

