version: "3.9"

services:
  
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - rede_bd

  backend:
    container_name: api
    build: ./back-end
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env
    depends_on:
      - postgres
    networks:
      - rede_bd
  
  front-end:
    container_name: spa
    restart: always
    build: ./front-end
    env_file:
      - ./front-end/.env.local
    volumes:
      - next-volume:/var/www/html
    networks:
      - rede_bd

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443

    volumes:
      - next-volume:/var/www/html
    depends_on:
      - backend
      - front-end
      - postgres

volumes:
  next-volume: 
  postgres-volume:
  
networks:
  rede_bd:
    driver: brigde
